name: GDIPTV-SP_update

on:
  schedule:
    - cron: '0 9 * * *' 
  push:
    branches:
      - main  # 在推送到main分支时也运行
  watch:
    types: [ started ]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.13' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run the script
        run: python $GITHUB_WORKSPACE/GDIPTV-SP.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update GDIPTV.m3u and GDIPTV-SP.m3u files" || echo "No changes to commit"
          git push
