name: GDIPTV-SP_update

on:
  schedule:
    - cron: '0 9 */2 * *' 
  push:
    branches:
      - main
    paths: 
      - '**.js'
  watch:
    types: [ started ]
  workflow_dispatch:  

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.13' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run the script
        run: python $GITHUB_WORKSPACE/GDIPTV-SP.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ip-port.txt GDIPTV.m3u GDIPTV-SP.m3u
          git commit -m "Update files" || echo "No changes to commit"  
          git pull --rebase origin main
          git push origin main
