name: m3u2txt

on:
  schedule:
    - cron: '0 22 * * *' 
  watch:
    types: [started]

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 拉取代码

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # 选择要使用的 Python 版本

    - name: Run Python script
      run: python m3u2txt.py  # 替换为你的 Python 脚本的路径

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update results"
        git push
