name: m3u2txt

on:
  schedule:
    - cron: '0 22 * * *' 
  watch:
    types: [started]

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 拉取代码

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # 选择要使用的 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # 安装依赖库

    - name: Run Python script
      run: python mytv.py  # 替换为你的 Python 脚本的路径

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add mytvfree.m3u
        git diff --quiet && git diff --staged --quiet || git commit -m "Update mytvfree.m3u"
        git push
